### ISSUE TITLE
Project does not work on OS X, Visual Studio for Mac

### ISSUE THREAD

**Issue by DaveVoyles** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2#10]
This other sample, [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore), which I believe is nearly identical, does, though.

I do not receive any errors when trying to build. It simply builds, says 'successful', then stops. 

I've restored and updates packages.

STEPS TO REPRODUCE:
1. Clone repo
2. Build project
3. Update NuGet packages
4. Run

![screenshot 2018-01-16 14 28 05](https://user-images.githubusercontent.com/1786053/35008153-914af260-fac9-11e7-92ea-3a524353b8f7.png)

**Comment by jmprieur** [comment]
Do you want to try  https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 which replaces this sample
