### ISSUE TITLE
SignOut does not  logout of MS auth

### ISSUE THREAD

**Issue by yiylin** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2#6]
I run this project. After I click sign out, and I sign in to go to https://login.microsoftonline.com/ . The web page shows that my account has been signed in.

**Comment by jmprieur** [comment]
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2, which now replaces this project, does the sign-out correctly
