### ISSUE TITLE
ASP.NET Core 1.1

### ISSUE THREAD

**Issue by Waldulmer** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2#7]
Can you please update this sample app to version ASP.NET Core 1.1.

**Comment by UNGM2000** [comment]
Request to conversation digital data.

**Comment by jmprieur** [comment]
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 replaces this project. it's for ASP.NET Core 2.x
