### ISSUE TITLE
Project is out of date for Core 2.0 and OpenIDConnect 2.0

### ISSUE THREAD

**Issue by Thraka** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2#9]
Please update. Many things seem deprecated and a few field/prop names have changed on the objects too.

@gsacavdm

**Comment by mark-szabo** [comment]
@Thraka till this gets updated, you can check out this Microsoft Graph sample, which implements ASP.NET Core 2.0 and AzureAD v2 (MSAL): https://github.com/microsoftgraph/aspnetcore-connect-sample

**Comment by jmprieur** [comment]
I'm archiving this project, as this sample is for ASP.NET Core 2.x and OpenIdConnect 2.0:
 https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2.
